import { StyleSheet } from "react-native";
import { AppColorTokens } from "@/constants/theme";

export function makeCamStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 50,
    paddingBottom: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  backBtn: { padding: 8, borderRadius: 12, backgroundColor: colors.surface },
  iconBtn: { padding: 8, borderRadius: 12, backgroundColor: colors.surface },
  iconBtnActive: {
    backgroundColor: colors.border.cyan,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  modeBtnActive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    backgroundColor: colors.border.cyanMedium,
    borderWidth: 1,
    borderColor: colors.border.cyanStrong,
    maxWidth: 140,
  },
  modeBtnText: { fontSize: 11, fontWeight: "bold", color: colors.primary },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: "bold", color: colors.text.primary },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { fontSize: 11, fontWeight: "bold", textTransform: "uppercase" },
  cameraContainer: {
    marginHorizontal: 16,
    borderRadius: 24,
    backgroundColor: colors.surfaceAlt,
    overflow: "hidden",
    position: "relative",
  },
  permissionBox: { flex: 1, alignItems: "center", justifyContent: "center", gap: 16 },
  warn: { color: colors.text.secondary, textAlign: "center", fontSize: 14, paddingHorizontal: 20 },
  gestureOverlay: {
    position: "absolute",
    bottom: 24,
    alignSelf: "center",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  gestureLabel: {
    fontSize: 40,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 2,
  },
  confidencePill: {
    backgroundColor: colors.border.cyan,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  confidenceText: { fontSize: 14, color: colors.primary, fontWeight: "bold" },
  edgeBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: colors.border.cyan,
    borderWidth: 1,
    borderColor: colors.border.cyanStrong,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  edgeBadgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: colors.primary,
    textTransform: "uppercase",
  },
  errorBanner: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    backgroundColor: "rgba(255, 50, 50, 0.15)",
    borderWidth: 1,
    borderColor: colors.accent.error,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: { color: colors.accent.error, fontSize: 12, flex: 1, fontWeight: "500" },
  noHandBadge: {
    position: "absolute",
    bottom: 72,
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  noHandText: { color: colors.text.secondary, fontSize: 12 },
  modelBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: "rgba(179, 136, 255, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(179, 136, 255, 0.35)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: 140,
  },
  modelBadgeText: { fontSize: 10, fontWeight: "bold", color: colors.accent.purple },
  modelErrorBanner: {
    position: "absolute",
    top: 44,
    left: 12,
    right: 12,
    backgroundColor: "rgba(255, 50, 50, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 107, 107, 0.4)",
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  modelErrorTitle: { color: colors.accent.error, fontSize: 13, fontWeight: "700" },
  modelErrorDesc: { color: colors.accent.error, fontSize: 11, marginTop: 2 },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 10 },
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  modalTitle: { fontSize: 22, fontWeight: "800", color: colors.text.primary },
  modalSubtitle: {
    fontSize: 13,
    color: colors.text.secondary,
    marginBottom: 20,
    lineHeight: 18,
  },
  modeOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surfaceAlt,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "transparent",
    marginBottom: 10,
  },
  modeOptionActive: {
    backgroundColor: colors.border.cyanMedium,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  modeOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  modeLabel: { fontSize: 15, fontWeight: "700", color: colors.text.tertiary },
  modeLabelActive: { color: colors.primary },
  modeDesc: { fontSize: 11, color: colors.text.secondary, marginTop: 2 },
  activeDotOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.border.cyanMedium,
    alignItems: "center",
    justifyContent: "center",
  },
  activeDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  modalCloseBtn: {
    marginTop: 10,
    alignItems: "center",
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  modalCloseBtnText: { color: colors.text.secondary, fontSize: 15, fontWeight: "600" },
  landmarksRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surfaceAlt,
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
    gap: 12,
  },
  landmarksRowText: { flex: 1 },
  landmarksRowTitle: { fontSize: 15, fontWeight: "700", color: colors.text.primary },
  landmarksRowDesc: { fontSize: 11, color: colors.text.secondary, marginTop: 2 },
  });
}
